services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
      - ./data:/data
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.rileymathews.com`) || Host(`local.nextcloud.rileymathews.com`)
      - traefik.http.routers.nextcloud.tls.certresolver=cf
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-bookworm
    container_name: nextcloud-postgres
    restart: always
    tty: true
    env_file:
      - .env.pg.secret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
